[package]
name = "tessellation"
version = "0.7.2"
authors = ["Henning Meyer <tutmann@gmail.com>"]

description = "3d tessellation library."
repository = "https://github.com/hmeyer/tessellation"
readme = "README.md"
keywords = ["tessellation", "3d", "manifold", "dual-contouring"]
license = "GPL-3.0"

[lib]
name = "tessellation"
path = "src/lib.rs"

[dependencies]
alga = "0.9"
nalgebra = "0.19"
rand = "0.7"
time = "0.1"
rayon = "1.2"
lazy_static = "1.4"
bbox = "0.9"
num-traits = "0.2"

[dev-dependencies]
approx = "0.3"
bencher = "0.1"
implicit3d = "0.13"

[[bench]]
name = "tessellation"
path = "src/benches/tessellation.rs"
harness = false

[badges]
travis-ci = { repository = "hmeyer/tessellation", branch = "master" }
codecov = { repository = "hmeyer/tessellation", branch = "master", service = "github" }
